[package]
name = "cbindgen-cffi-compat"
version = "0.1.0"
authors = ["Danny McClanahan <1305167+cosmicexplorer@users.noreply.github.com>"]
edition = "2018"

[dependencies]
cbindgen = "0.12.1"
regex = "1"
