[package]
name = "terminal-wrapper"
version = "0.1.0"
authors = ["Danny McClanahan <1305167+cosmicexplorer@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3.1"
thrift = "0.13.0"

[build-dependencies]
cbindgen = "0.12.0"
walkdir = "2"
