[package]
name = "terminal-wrapper"
version = "0.1.0"
authors = ["Danny McClanahan <1305167+cosmicexplorer@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = []
cffi_compatible = ["thrift_ffi/cffi_compatible"]
pants-injected = ["thrift_ffi", "cffi_compat"]

[dependencies]
regex = "1"
thrift = "0.13.0"
thrift_ffi = { path = "thrift_ffi", optional = true }

[build-dependencies]
cffi_compat = { path = "thrift_ffi/cffi_compat", optional = true }
