[package]
name = "terminal-wrapper"
version = "0.1.0"
authors = ["Danny McClanahan <1305167+cosmicexplorer@users.noreply.github.com>"]
edition = "2018"

[workspace]
members = [
  ".",
  "thrift_ffi",
]
# These are the packages which are built/tested when no special selector flags are passed to cargo.
default-members = [
  ".",
  "thrift_ffi",
]

[dependencies]
# thrift = "0.13.0"
thrift_ffi = { path = "thrift_ffi" }
