header = '''
#ifndef __TERMINAL_WRAPPER_CBINDGEN_H__
#define __TERMINAL_WRAPPER_CBINDGEN_H__
'''
trailer = '''
#endif // __TERMINAL_WRAPPER_CBINDGEN_H__
'''
include_version = true
line_length = 100
language = "C"

[parse]
parse_deps = false
