# This package will be replaced with the package from //thrift_ffi:thrift_ffi!
[package]
name = "thrift_ffi"
version = "0.1.0"
authors = ["Danny McClanahan <1305167+cosmicexplorer@users.noreply.github.com>"]
edition = "2018"

[lib]
path = "./empty.rs"
